### ISSUE TITLE
eks-demo 

### ISSUE THREAD

**Issue by ynr4** [wardviaene/terraform-course#15]
Hi Edward,

eks-demo encountering bellow errors when I am trying to run terraform apply. Kindly take a look into it.

[root@linux01 eks-demo]# terraform apply

Error: Unsupported block type

  on securitygroups.tf line 13, in resource "aws_security_group" "demo-cluster":
  13:   tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.

Error: Missing resource instance key

  on .terraform/modules/vpc/terraform-aws-modules-terraform-aws-vpc-d723605/main.tf line 31, in resource "aws_vpc_ipv4_cidr_block_association" "this":
  31:   vpc_id = "${aws_vpc.this.id}"

Because aws_vpc.this has "count" set, its attributes must be accessed on
specific instances.

For example, to correlate with indices of a referring resource, use:
    aws_vpc.this[count.index]

Error: Unsupported argument

  on .terraform/modules/vpc/terraform-aws-modules-terraform-aws-vpc-d723605/main.tf line 295, in resource "aws_default_network_acl" "this":
 295:   ingress = "${var.default_network_acl_ingress}"

An argument named "ingress" is not expected here. Did you mean to define a
block of type "ingress"?

Error: Unsupported argument

  on .terraform/modules/vpc/terraform-aws-modules-terraform-aws-vpc-d723605/main.tf line 296, in resource "aws_default_network_acl" "this":
 296:   egress  = "${var.default_network_acl_egress}"

An argument named "egress" is not expected here. Did you mean to define a
block of type "egress"?

[root@linux01 eks-demo]#

Regards,
Nagaraju
-Student of your Udemy Course

**Comment by wardviaene** [comment]
Are you on the terraform-0.12 branch? If you have a terraform version >0.12 then you should take that branch

**Comment by ynr4** [comment]
I am using latest version terraform, I fixed issue in some other way. We may close the incident. Thanks for your quick response. :)
