### ISSUE TITLE
Provider "cloudinit" not available for installation

### ISSUE THREAD

**Issue by rajcdlmec** [wardviaene/terraform-course#3]
# terraform init

Initializing provider plugins...
- Downloading plugin for provider "cloudinit"...

Provider "cloudinit" not available for installation.

A provider named "cloudinit" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/linux_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

**Comment by wardviaene** [comment]
You can remove the line that initialized the cloudinit provider, it doesn't exist anymore and it's not necessary to have it
