### ISSUE TITLE
interested in your course but want to use it with another provider

### ISSUE THREAD

**Issue by vesper8** [wardviaene/terraform-course#8]
How tied to AWS is your course content? I would like to learn this devops stack but wish to use it with other VPS providers such as DigitalOcean/Linode/Vultr

**Comment by wardviaene** [comment]
It's indeed tied to AWS. The DigitalOcean resources are much easier to use than the AWS ones, so if you'd take the course and follow the more general ideas/examples, then you should have no issues applying them to other cloud providers.
